
project_id = "ryqawthghqhsgjucgong"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt_expiry = 3600
password_min_length = 6
external_email_enabled = true
external_phone_enabled = true
sms_test_otp = "123456"
external_twitter_enabled = false
external_google_enabled = false

[db]
port = 54322

[edge_functions]
enabled = true

[functions.stripe-webhook]
verify_jwt = false
